name: fusion_booking
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^3.0.1
  velocity_x: ^4.1.2
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  flutter_slidable:
    path: custom_package/flutter_slidable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
    - assets/font/
    - assets/
    - assets/icons/clock 1.png
  fonts:
    - family: Yellowtail Regular
      fonts:
        - asset: assets/font/Yellowtail-Regular.ttf
    - family: Lato Regular
      fonts:
        - asset: assets/font/Lato-Regular.ttf
